build:
  nodes:
    tests:
      override:
        - npm install  # Install project dependencies (if needed)
        - npm test     # Run your test command
          coverage:
            file: 'backend/coverage/clover.xml'  # Path to your Clover coverage report
            format: clover
  filter:
    exclude:
      - 'backend/node_modules/'
      - 'backend/coverage/'
      - 'backend/.nyc_output/'

source_on_workers:
  environment:
    nodejs: v16  # Adjust to your Node.js version
  pre_setup:
    - 'npm install -g source-cli'  # Install Source CLI globally
  override:
    - 'source-cli run'  # Run Source on Workers

tools:
  external_code_coverage:
    timeout: 300000  # Optional: Increase timeout if your tests take longer