# docker-compose.yml
version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: sparkgo_mysql
    networks:
      - sparkgo
    ports:
      - 3307:3306 # <host_port>:<container_port>
    volumes:
      - ./sparkgo.sql:/docker-entrypoint-initdb.d/sparkgo.sql
      #- ../sql/:/host_sql_folder # just so we can make an easy new db version
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: sparkgo
      MYSQL_USER: dbadm
      MYSQL_PASSWORD: P@ssw0rd
    extra_hosts: # add this section
      - "host.docker.internal:host-gateway"

networks:
  sparkgo:
