# docker-compose.yml
version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    networks:
      - sparkgo
    ports:
      - 3306:3306
    volumes:
      - ./sparkgo.sql:/docker-entrypoint-initdb.d/sparkgo.sql
      #- ../sql/:/host_sql_folder # just so we can make an easy new db version
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: sparkgo
      MYSQL_USER: user
      MYSQL_PASSWORD: password

networks:
  sparkgo:
