name: Backend CI/CD

on:
    push:
        branches:
            - master
            - dev
            - feature-backend-testing

jobs:
    build:
        runs-on: ubuntu-20.04

        env:
            NODE_OPTIONS: "--max-old-space-size=4096" # Increase Node.js memory limit

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 16.20.2

            - name: Set up MariaDB
              run: |
                  docker pull mariadb:latest
                  docker run --name mariadb -d -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root_password -e MYSQL_DATABASE=test -e MYSQL_USER=dbadm -e MYSQL_PASSWORD=P@ssw0rd mariadb:latest

            - name: Run SQL scripts to populate databases
              working-directory: sql
              run: |
                  docker exec mariadb sh -c 'mysql -h localhost -u dbadm -pP@ssw0rd test <reset.sql'

            - name: Install backend dependencies
              working-directory: backend
              run: npm install

            - name: Run backend tests
              working-directory: backend
              run: npm test
