name: Backend CI/CD

on:
    push:
        branches:
            - main
            - dev
            - feature-backend-testing

jobs:
    build:
        runs-on: ubuntu-20.04

        env:
            NODE_OPTIONS: "--max-old-space-size=4096" # Increase Node.js memory limit

        services:
            mariadb:
                image: mariadb:latest
                ports:
                    - 3306:3306
                env:
                    MYSQL_ROOT_PASSWORD: password # Set your desired root password
                    MYSQL_DATABASE: test # Set your desired database name
                    MYSQL_USER: dbadm # Set your desired username
                    MYSQL_PASSWORD: P@ssw0rd # Set your desired password

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 16.20.2

            - name: Install backend dependencies
              working-directory: backend
              run: npm install

            - name: Run backend tests
              working-directory: backend
              run: npm test
