name: Backend CI/CD

on:
    push:
        branches:
            - master
            - dev
            - feature-backend-testing

jobs:
    build:
        runs-on: ubuntu-20.04

        services:
            mariadb:
                image: mariadb:latest
                env:
                    MYSQL_ROOT_PASSWORD: root_password
                    MYSQL_DATABASE: test
                    MYSQL_USER: dbadm
                    MYSQL_PASSWORD: P@ssw0rd
                ports:
                    - 3306:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

        env:
            NODE_OPTIONS: "--max-old-space-size=4096" # Increase Node.js memory limit
            DB_HOST: localhost
            DB_PORT: 3306
            DB_USER: dbadm
            DB_PASSWORD: P@ssw0rd
            DB_DATABASE: test

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 16.20.2

            - name: Install backend dependencies
              working-directory: backend
              run: npm install

            - name: Run backend tests
              working-directory: backend
              run: npm test
