name: Backend CI/CD

on:
    push:
        branches:
            - main
            - dev
            - feature-backend-testing

jobs:
    build:
        runs-on: ubuntu-20.04

        env:
            NODE_OPTIONS: "--max-old-space-size=4096" # Increase Node.js memory limit
            DB_HOST: localhost
            DB_PORT: 3306
            DB_USER: dbadm
            DB_PASSWORD: P@ssw0rd
            DB_DATABASE: test

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 16.20.2

            - name: Install backend dependencies
              working-directory: backend
              run: npm install

            - name: Run backend tests
              working-directory: backend
              run: npm test
