name: Backend CI/CD

on:
    push:
        branches:
            - main
            - dev
            - feature-backend-testing

jobs:
    build:
        runs-on: ubuntu-20.04

        env:
            NODE_OPTIONS: "--max-old-space-size=4096" # Increase Node.js memory limit

        services:
            mysql:
                image: mysql:latest
                env:
                    MYSQL_ROOT_PASSWORD: root_password
                    MYSQL_DATABASE: test_db
                    MYSQL_USER: db_user
                    MYSQL_PASSWORD: db_password
                ports:
                    - 3306:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 16.20.2

            - name: Install backend dependencies
              working-directory: backend
              run: npm install

            - name: Wait for MySQL to start
              run: |
                  echo "Waiting for MySQL to start"
                  dockerize -wait tcp://127.0.0.1:3306 -timeout 1m

            - name: Run database migration
              working-directory: backend
              run: npm run migrate # Assuming you have a script to handle migrations

            - name: Run backend tests
              working-directory: backend
              run: npm test
